### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by leonadler** [gentics/gentics-ui-image-editor#1]
Hi - As already stated before, thanks for this very awesome implementation!

I have a few suggestions / proposals:

1. Rename the `(transformation)` output to `(transformationChange)` and add an input `transformation` - there is currently no way to supply already existing scaling/cropping/focalpoint information to the editor.  
`@Input() transformation` & `@Output() transformationChange` would allow consumers to use double-binding.

2. Disable text selection for the interactive elements (e.g. mode buttons, "aspect ration" text)
When a user switches between modes and has the mouse down for a tad too long, the text below the buttons gets selected

3. When in mode X, switch back to the overview when `canX` changes to `false`

4. Exact scaling via text input
e.g. width shows "1,921px", but as `<input value=1,921><span>px</span>`
User could update the value to an exact value (1920px)

5. Use default (non-interactive) cursor for mode button when in a mode
e.g. after clicking on "scale", the button on the left side still shows the hand cursor, but can not be interacted with it

I'd be happy to hear your opinion/input.

**Comment by michaelbromley** [comment]
Hey, thanks for the continued praise! 😄 

1. As I predicted, I needed this right away in the MeshUI, so this is now implemented. See the demo https://gentics.github.io/gentics-ui-image-editor/
2. Good idea, next version.
3. Not an expected case beyond the demo, since these toggles should really be set and then left, but who knows. Worth doing.
4. Yeah nice idea, you mean the labels on the axes next to the image?
5. Yep. in the next version.
